jdkVersion="17"
customTools=["/extra-tools/clomonitor.sh"] # enable CLOMonitor scanning
tools=[] # do not include any other scanning tools
​
ignoreRules = [
	"Security: Signed Releases",
	"Security: Security Policy",
	"Security: Sbom",
	"Security: Maintained",
	"Security: Dependency Update Tool",
	"Security: Code Review",
	"Security: Branch Protection",
	"License: License Scanning",
	"Legal: Trademark Disclaimer",
	"Documentation: Website",
	"Documentation: Roadmap",
	"Documentation: Governance",
	"Documentation: Code Of Conduct",
	"Documentation: Changelog",
	"Documentation: Adopters",
	"Best Practices: Slack Presence",
	"Best Practices: Openssf Badge",
	"Best Practices: Github Discussions",
	"Best Practices: Community Meeting",
	"Best Practices: Artifacthub Badge",
	"Best Practices: Analytics"
]
​